---
title: "Combined heatmaps and scatter plots of all experiemental manipulations"
output: html_notebook
---

```{r}
# Load data and libraries
rm(list=ls())
require(readxl)
require(tidyverse)
require(tm)
require(ggfortify)
require(reshape2)
require(ggbeeswarm)
require(EnhancedVolcano)
require(RColorBrewer)
require(fgsea)
require(ComplexHeatmap)
require(reshape2)
files.sources = list.files("../functions" , full.names = TRUE)
invisible(lapply(files.sources, source))
```

```{r}
trio.xls <- read_xlsx("../data/results_PSD-Trio-proteome_Two-sample_mod_T_2020-07-24.xlsx")
shank3.xls <- read_xlsx("../data/results_PSD-Shank3-proteome_Two-sample_mod_T_2020-07-22.xlsx")
grin2a.xls <- read_xlsx("../data/results_Glun2a-TMT16-Proteome_Two-sample_mod_T_2020-11-30.xlsx")
goPathways <- "~/Google Drive/geneSets/mSigDb/v7_2/ontology/c5.all.v7.2.symbols.gmt"
pathways.go <- gmtPathways(goPathways)
RNA_SPLICING <- str_to_title(pathways.go$GO_RNA_SPLICING)
CYTOSOLIC_RIBOSOME <- str_to_title(pathways.go$GO_CYTOSOLIC_RIBOSOME)
STRESS_GRANULE_ASSEMBLY <- str_to_title(pathways.go$GO_STRESS_GRANULE_ASSEMBLY)
GLUTAMATERGIC_SYNAPSE <- str_to_title(pathways.go$GO_GLUTAMATERGIC_SYNAPSE)
VOLTAGE_GATED_ION_CHANNEL_ACTIVITY <- str_to_title(pathways.go$GO_VOLTAGE_GATED_ION_CHANNEL_ACTIVITY)

MITOCHONDRIAL_PROTEIN_COMPLEX <- str_to_title(pathways.go$GO_MITOCHONDRIAL_PROTEIN_COMPLEX)
SMALL_GTPASE_BINDING <- str_to_title(pathways.go$GO_SMALL_GTPASE_BINDING)
INTRINSIC_COMPONENT_OF_POSTSYNAPTIC_MEMBRANE <- str_to_title(pathways.go$GO_INTRINSIC_COMPONENT_OF_POSTSYNAPTIC_MEMBRANE)
PROTEIN_LOCALIZATION_TO_SYNAPSE <- str_to_title(pathways.go$GO_PROTEIN_LOCALIZATION_TO_SYNAPSE)
NEURON_PROJECTION_EXTENSION <- str_to_title(pathways.go$GO_NEURON_PROJECTION_EXTENSION)
MITOCHONDRIAL_MATRIX <- str_to_title(pathways.go$GO_MITOCHONDRIAL_MATRIX)
OXIDATIVE_PHOSPHORYLATION <- str_to_title(pathways.go$GO_OXIDATIVE_PHOSPHORYLATION)
MGLUR <- paste("Grm", c(1:8), sep="")
GABAA_RECEPTOR <- c(paste("Gabra", c(1:5), sep=""), paste("Gabrb", c(1:3), sep=""), paste("Gabrg", c(1:3), sep=""), paste("Gabrb", c("d","e","p","q"), sep=""), paste("Gabrr", c(1:3), sep=""))
ANTIGEN_PROCESSING_AND_PRESENTATION_OF_EXOGENOUS_PEPTIDE_ANTIGEN_VIA_MHC_CLASS_I <- str_to_title(pathways.go$GO_ANTIGEN_PROCESSING_AND_PRESENTATION_OF_EXOGENOUS_PEPTIDE_ANTIGEN_VIA_MHC_CLASS_I)
FC_RECEPTOR_SIGNALING_PATHWAY <- str_to_title(pathways.go$GO_FC_RECEPTOR_SIGNALING_PATHWAY)
GLUTAMATE_RECEPTOR_SIGNALING_PATHWAY <- str_to_title(pathways.go$GO_GLUTAMATE_RECEPTOR_SIGNALING_PATHWAY)
MACROAUTOPHAGY <- str_to_title(pathways.go$GO_MACROAUTOPHAGY)

```



```{r}
pVal <- 0.1

setVars<-function(dat.xls){
  dat.xls <- dat.xls %>% drop_na(logFC.WT.over.KO, logFC.WT.over.Het, logFC.KO.over.Het)
  dat.xls <- dat.xls %>% mutate(logFC.KO.over.WT = logFC.WT.over.KO*(-1))
  dat.xls <- dat.xls %>% mutate(logFC.Het.over.WT = logFC.WT.over.Het*(-1))
  dat.xls <- dat.xls %>% mutate(t.KO.over.WT = t.WT.over.KO*(-1))
  dat.xls <- dat.xls %>% mutate(t.Het.over.WT = t.WT.over.Het*(-1))
  dat.xls <- dat.xls %>% mutate(ko.sig = ifelse(P.Value.WT.over.KO < pVal, 1, 0))
  dat.xls <- dat.xls %>% mutate(het.sig = ifelse(P.Value.WT.over.Het < pVal, 2, 0))
  dat.xls <- dat.xls %>% mutate(hetOverWT.sig = ifelse(P.Value.WT.over.Het < pVal, 1, 0))
  dat.xls <- dat.xls %>% mutate(both.sig = as.factor(ko.sig + het.sig))
  dat.xls <- dat.xls %>% mutate(koOverHet.sig = ifelse(P.Value.KO.over.Het < pVal, 2, 0))
  dat.xls <- dat.xls %>% mutate(both.koOverHet.sig = as.factor(hetOverWT.sig + koOverHet.sig))
  dat.xls <- dat.xls %>% mutate(RNA_SPLICING = ifelse(geneSymbol %in% RNA_SPLICING, 1, 0))
  dat.xls <- dat.xls %>% mutate(CYTOSOLIC_RIBOSOME = ifelse(geneSymbol %in% CYTOSOLIC_RIBOSOME, 1, 0))
  #dat.xls <- dat.xls %>% mutate(spl.ribo = RNA_SPLICING + CYTOSOLIC_RIBOSOME)
  dat.xls <- dat.xls %>% mutate(STRESS_GRANULE_ASSEMBLY = ifelse(geneSymbol %in% STRESS_GRANULE_ASSEMBLY, 1, 0))
  dat.xls <- dat.xls %>% mutate(GLUTAMATERGIC_SYNAPSE = ifelse(geneSymbol %in% GLUTAMATERGIC_SYNAPSE, 1, 0))
  dat.xls <- dat.xls %>% mutate(VOLTAGE_GATED_ION_CHANNEL_ACTIVITY = ifelse(geneSymbol %in% VOLTAGE_GATED_ION_CHANNEL_ACTIVITY, 1, 0))
  
  dat.xls <- dat.xls %>% mutate(MITOCHONDRIAL_PROTEIN_COMPLEX = ifelse(geneSymbol %in% MITOCHONDRIAL_PROTEIN_COMPLEX, 1, 0))
  dat.xls <- dat.xls %>% mutate(SMALL_GTPASE_BINDING = ifelse(geneSymbol %in% SMALL_GTPASE_BINDING, 1, 0))
  dat.xls <- dat.xls %>% mutate(INTRINSIC_COMPONENT_OF_POSTSYNAPTIC_MEMBRANE = ifelse(geneSymbol %in% INTRINSIC_COMPONENT_OF_POSTSYNAPTIC_MEMBRANE, 1, 0))
  dat.xls <- dat.xls %>% mutate(PROTEIN_LOCALIZATION_TO_SYNAPSE = ifelse(geneSymbol %in% PROTEIN_LOCALIZATION_TO_SYNAPSE, 1, 0))
  dat.xls <- dat.xls %>% mutate(NEURON_PROJECTION_EXTENSION = ifelse(geneSymbol %in% NEURON_PROJECTION_EXTENSION, 1, 0))
  dat.xls <- dat.xls %>% mutate(MITOCHONDRIAL_MATRIX = ifelse(geneSymbol %in% MITOCHONDRIAL_MATRIX, 1, 0))
  dat.xls <- dat.xls %>% mutate(OXIDATIVE_PHOSPHORYLATION = ifelse(geneSymbol %in% OXIDATIVE_PHOSPHORYLATION, 1, 0))
  dat.xls <- dat.xls %>% mutate(MGLUR = ifelse(geneSymbol %in% MGLUR, 1, 0))
  dat.xls <- dat.xls %>% mutate(GABAA_RECEPTOR = ifelse(geneSymbol %in% GABAA_RECEPTOR, 1, 0))
  dat.xls <- dat.xls %>% mutate(ANTIGEN_PROCESSING_AND_PRESENTATION_OF_EXOGENOUS_PEPTIDE_ANTIGEN_VIA_MHC_CLASS_I = ifelse(geneSymbol %in% ANTIGEN_PROCESSING_AND_PRESENTATION_OF_EXOGENOUS_PEPTIDE_ANTIGEN_VIA_MHC_CLASS_I, 1, 0))
  dat.xls <- dat.xls %>% mutate(FC_RECEPTOR_SIGNALING_PATHWAY = ifelse(geneSymbol %in% FC_RECEPTOR_SIGNALING_PATHWAY, 1, 0))
  dat.xls <- dat.xls %>% mutate(GLUTAMATE_RECEPTOR_SIGNALING_PATHWAY = ifelse(geneSymbol %in% GLUTAMATE_RECEPTOR_SIGNALING_PATHWAY, 1, 0))
  dat.xls <- dat.xls %>% mutate(MACROAUTOPHAGY = ifelse(geneSymbol %in% MACROAUTOPHAGY, 1, 0))
  
  return (dat.xls)
}

trio.xls <- setVars(trio.xls)
shank3.xls <- setVars(shank3.xls)
grin2a.xls <- setVars(grin2a.xls)
```

```{r}
getVars<-function(dat.xls, goTerm){
  curDat <- dat.xls %>% select(geneSymbol, 
                             logFC.KO.over.WT, 
                             logFC.Het.over.WT,
                             logFC.KO.over.Het,
                             all_of(goTerm),
                             )
  curDat <-  curDat %>% mutate(x=logFC.KO.over.WT, y=logFC.Het.over.WT)
  curDat <- curDat %>% mutate(color=.[[5]])
  return(curDat)
}

plotWidth <- 9
plotHeight <- 9

makeHetKoPlot <- function(dat.xls, goName){
  fcCutOff <- 1.5
  dat.curDat <- getVars(dat.xls, goName)
  lab <- c("", goName)
  scPlot <- makeScatterPlot(dat.curDat, lab)
  scPlot <- scPlot + xlab("Log2-fold change (KO/WT)") + ylab("Log2-fold change (Het/WT)")
  scPlot <- scPlot + geom_text_repel(aes(label=ifelse(((color==1 & x> 1) | (color==1 & y > 1) | (color==1 & x < -1) | (color==1 & y < -1)), as.character(geneSymbol), '')), show.legend = FALSE, segment.color='black', segment.size = .5, segment.alpha = .25, size=3)
  scPlot <- scPlot + coord_cartesian(ylim=c(-5,5), xlim=c(-5,5))
  return(scPlot)
}

makeAllHetKoPlots <- function(input.xls, inputCount, inputName){
  count <- inputCount
  cols <- dim(input.xls)[2]
  while (count <= cols){
    goName <- colnames(input.xls)[count]
    dat.plot <- makeHetKoPlot(input.xls, goName)
    ggsave(plot = dat.plot, paste("~/Google Drive/psp/analysis/plots/", inputName, "/lfcScatter_ko_v_het_", goName, ".pdf", sep=""), width = plotWidth, height = plotHeight, units = "in")
    count <- count + 1
  }
}


makeAllHetKoPlots(trio.xls, 66, "trio")
makeAllHetKoPlots(shank3.xls, 66, "shank3")
makeAllHetKoPlots(grin2a.xls, 68, "grin2a")

```



```{r}
# setColNames <- function(tbl, suffix){
#   colnames.tbl.tmp <- paste(colnames(tbl), suffix, sep="")
#   colnames.tbl.tmp[1] <- "id"
#   colnames(tbl) <- colnames.tbl.tmp
#   return (tbl)
# }
# 
# trio.xls <- setColNames(trio.xls, ".trio")
# shank3.xls <- setColNames(shank3.xls, ".shank3")
# grin2a.xls <- setColNames(grin2a.xls, ".grin2a")
# 
all.xls <- inner_join(trio.xls, shank3.xls, by="id")
all.xls <- inner_join(all.xls, grin2a.xls, by="id")

all.xls <- full_join(trio.xls, shank3.xls, by="id")
all.xls <- full_join(all.xls, grin2a.xls, by="id")
```


```{r}
pWidth = 3
pHeight = 6

trio.abundances <- trio.xls %>% dplyr::select(starts_with("Trio_PSD_TMT11_Proteome.."))
trio.sampleSheet <- makeSampleSheet(trio.abundances)
colnames(trio.abundances) <- trio.sampleSheet$cleanId

trio.trio.abundance.m <- getAbundanceOfProtein(trio.xls, 
                                             'Q0KL02',
                                             "Trio_PSD_TMT11_Proteome..", 
                                             trio.sampleSheet)
trio.trio.abundance.plot <- makeAbundancePlot(trio.trio.abundance.m)
ggsave("~/Google Drive/psp/analysis/plots/combined/abundance_trio.pdf", width = pWidth, height = pHeight, units="in")

shank3.abundances <- shank3.xls %>% dplyr::select(starts_with("Shank3_PSD_TMT11_Proteome.."))
shank3.sampleSheet <- makeSampleSheet(shank3.abundances)
colnames(shank3.abundances) <- shank3.sampleSheet$cleanId

shank3.shank3.abundance.m <- getAbundanceOfProtein(shank3.xls, 
                                             'A0A0A0MQD5',
                                             "Shank3_PSD_TMT11_Proteome..", 
                                             shank3.sampleSheet)
shank3.shank3.abundance.plot <- makeAbundancePlot(shank3.shank3.abundance.m)
ggsave("~/Google Drive/psp/analysis/plots/combined/abundance_shank3.pdf", width = pWidth, height = pHeight, units="in")


grin2a.abundances <- grin2a.xls %>% dplyr::select(starts_with("Glun2A_PSD_TMT16_Proteome.."))
grin2a.sampleSheet <- makeSampleSheet(grin2a.abundances)
colnames(grin2a.abundances) <- grin2a.sampleSheet$cleanId

grin2a.grin2a.abundance.m <- getAbundanceOfProtein(grin2a.xls, 
                                               'P35436',
                                               "Glun2A_PSD_TMT16_Proteome..", 
                                               grin2a.sampleSheet)
grin2a.grin2a.abundance.plot <- makeAbundancePlot(grin2a.grin2a.abundance.m)
ggsave("~/Google Drive/psp/analysis/plots/combined/abundance_grin2a.pdf", width = pWidth, height = pHeight, units="in")

```
```{r}
pWidth = 3
pHeight = 6

trio.abundances <- trio.xls %>% dplyr::select(starts_with("Trio_PSD_TMT11_Proteome.."))
trio.sampleSheet <- makeSampleSheet(trio.abundances)
colnames(trio.abundances) <- trio.sampleSheet$cleanId

trio.trio.abundance.m <- getAbundanceOfProtein(trio.xls, 
                                             'Q8VIJ6',
                                             "Trio_PSD_TMT11_Proteome..", 
                                             trio.sampleSheet)
trio.trio.abundance.plot <- makeAbundancePlot(trio.trio.abundance.m)
ggsave("~/Google Drive/psp/analysis/plots/combined/abundance_Sfpq_trio.pdf", width = pWidth, height = pHeight, units="in")

shank3.abundances <- shank3.xls %>% dplyr::select(starts_with("Shank3_PSD_TMT11_Proteome.."))
shank3.sampleSheet <- makeSampleSheet(shank3.abundances)
colnames(shank3.abundances) <- shank3.sampleSheet$cleanId

shank3.shank3.abundance.m <- getAbundanceOfProtein(shank3.xls, 
                                             'Q8VIJ6',
                                             "Shank3_PSD_TMT11_Proteome..", 
                                             shank3.sampleSheet)
shank3.shank3.abundance.plot <- makeAbundancePlot(shank3.shank3.abundance.m)
ggsave("~/Google Drive/psp/analysis/plots/combined/abundance_Sfpq_shank3.pdf", width = pWidth, height = pHeight, units="in")


grin2a.abundances <- grin2a.xls %>% dplyr::select(starts_with("Glun2A_PSD_TMT16_Proteome.."))
grin2a.sampleSheet <- makeSampleSheet(grin2a.abundances)
colnames(grin2a.abundances) <- grin2a.sampleSheet$cleanId

grin2a.grin2a.abundance.m <- getAbundanceOfProtein(grin2a.xls, 
                                               'Q8VIJ6',
                                               "Glun2A_PSD_TMT16_Proteome..", 
                                               grin2a.sampleSheet)
grin2a.grin2a.abundance.plot <- makeAbundancePlot(grin2a.grin2a.abundance.m)
ggsave("~/Google Drive/psp/analysis/plots/combined/abundance_Sfpq_grin2a.pdf", width = pWidth, height = pHeight, units="in")

```

```{r}
pWidth = 3
pHeight = 6

trio.abundances <- trio.xls %>% dplyr::select(starts_with("Trio_PSD_TMT11_Proteome.."))
trio.sampleSheet <- makeSampleSheet(trio.abundances)
colnames(trio.abundances) <- trio.sampleSheet$cleanId

trio.trio.abundance.m <- getAbundanceOfProtein(trio.xls, 
                                             'P56959',
                                             "Trio_PSD_TMT11_Proteome..", 
                                             trio.sampleSheet)
trio.trio.abundance.plot <- makeAbundancePlot(trio.trio.abundance.m)
ggsave("~/Google Drive/psp/analysis/plots/combined/abundance_Fus_trio.pdf", width = pWidth, height = pHeight, units="in")

shank3.abundances <- shank3.xls %>% dplyr::select(starts_with("Shank3_PSD_TMT11_Proteome.."))
shank3.sampleSheet <- makeSampleSheet(shank3.abundances)
colnames(shank3.abundances) <- shank3.sampleSheet$cleanId

shank3.shank3.abundance.m <- getAbundanceOfProtein(shank3.xls, 
                                             'P56959',
                                             "Shank3_PSD_TMT11_Proteome..", 
                                             shank3.sampleSheet)
shank3.shank3.abundance.plot <- makeAbundancePlot(shank3.shank3.abundance.m)
ggsave("~/Google Drive/psp/analysis/plots/combined/abundance_Fus_shank3.pdf", width = pWidth, height = pHeight, units="in")


grin2a.abundances <- grin2a.xls %>% dplyr::select(starts_with("Glun2A_PSD_TMT16_Proteome.."))
grin2a.sampleSheet <- makeSampleSheet(grin2a.abundances)
colnames(grin2a.abundances) <- grin2a.sampleSheet$cleanId

grin2a.grin2a.abundance.m <- getAbundanceOfProtein(grin2a.xls, 
                                               'P56959',
                                               "Glun2A_PSD_TMT16_Proteome..", 
                                               grin2a.sampleSheet)
grin2a.grin2a.abundance.plot <- makeAbundancePlot(grin2a.grin2a.abundance.m)
ggsave("~/Google Drive/psp/analysis/plots/combined/abundance_Fus_grin2a.pdf", width = pWidth, height = pHeight, units="in")

```

```{r}
saveHeatMaps <- function(xlsFile, goTerm, goName){
  while (!is.null(dev.list()))  dev.off()
  
  plotWidth <- 9
  plotHeight <- (1.2)*plotWidth
  hMaps.goTerm <- makeHeatMap(xlsFile, goTerm)
  prefix <- "~/Google Drive/psp/analysis/plots/combined/heatmap_"
  suffixRaw <- "_Raw.pdf"

  pdf(file = paste(prefix, goName, suffixRaw, sep=""),   
      width = plotWidth, # The width of the plot in inches
      height = plotHeight) # The height of the plot in inches
  print(hMaps.goTerm[[1]])
  while (!is.null(dev.list()))  dev.off()
  
    
  suffixAv <- "_Average.pdf"
  pdf(file = paste(prefix, goName, suffixAv, sep=""),   
      width = plotWidth, # The width of the plot in inches
      height = plotHeight) # The height of the plot in inches
  print(hMaps.goTerm[[2]])
  while (!is.null(dev.list()))  dev.off()
  
  suffixTauLfc <- "_Average_TAU_LFC.pdf"
  pdf(file = paste(prefix, goName, suffixTauLfc, sep=""), 
      width = 1.5, # The width of the plot in inches
      height = plotHeight) # The height of the plot in inches
  print(hMaps.goTerm[[3]])
  while (!is.null(dev.list()))  dev.off()
  
  suffixAvLfc <- "_Average_LFC.pdf"
  pdf(file = paste(prefix, goName, suffixAvLfc, sep=""),   
      width = plotWidth, # The width of the plot in inches
      height = plotHeight) # The height of the plot in inches
  print(hMaps.goTerm[[4]])
  while (!is.null(dev.list()))  dev.off()
}
```

```{r}
saveHeatMaps(all.xls, RNA_SPLICING, "splicing")
mitoProComp <- str_to_title(pathways.go$GO_MITOCHONDRIAL_PROTEIN_COMPLEX)
saveHeatMaps(all.xls, MITOCHONDRIAL_PROTEIN_COMPLEX, "mitochondrial_protein_complex")
smallGtpaseBinding <- str_to_title(pathways.go$GO_SMALL_GTPASE_BINDING)
saveHeatMaps(all.xls, SMALL_GTPASE_BINDING, "small_gtpase_binding")
postSynapticIntrinsic <- str_to_title(pathways.go$GO_INTRINSIC_COMPONENT_OF_POSTSYNAPTIC_MEMBRANE)
saveHeatMaps(all.xls, INTRINSIC_COMPONENT_OF_POSTSYNAPTIC_MEMBRANE, "intrinsic_postsynaptic_membrane")
proLocSyn <- str_to_title(pathways.go$GO_PROTEIN_LOCALIZATION_TO_SYNAPSE)
saveHeatMaps(all.xls, PROTEIN_LOCALIZATION_TO_SYNAPSE, "protein_localization_to_synapse")
neuProEx <- str_to_title(pathways.go$GO_NEURON_PROJECTION_EXTENSION)
saveHeatMaps(all.xls, NEURON_PROJECTION_EXTENSION, "neuron_projection_extension")
mitoMat <- str_to_title(pathways.go$GO_MITOCHONDRIAL_MATRIX)
saveHeatMaps(all.xls, MITOCHONDRIAL_MATRIX, "mitochondrial_matrix")
oxPhos <- str_to_title(pathways.go$GO_OXIDATIVE_PHOSPHORYLATION)
saveHeatMaps(all.xls, OXIDATIVE_PHOSPHORYLATION, "oxidative_phosphorylation")
mglur <- paste("Grm", c(1:8), sep="")
saveHeatMaps(all.xls, MGLUR, "metabotropic_glutamate_receptors")
gabaa <- c(paste("Gabra", c(1:5), sep=""), paste("Gabrb", c(1:3), sep=""), paste("Gabrg", c(1:3), sep=""), paste("Gabrb", c("d","e","p","q"), sep=""), paste("Gabrr", c(1:3), sep=""))
saveHeatMaps(all.xls, GABAA_RECEPTOR, "gaba_A_receptors")

antigenProcessing <- str_to_title(pathways.go$GO_ANTIGEN_PROCESSING_AND_PRESENTATION_OF_EXOGENOUS_PEPTIDE_ANTIGEN_VIA_MHC_CLASS_I)
saveHeatMaps(all.xls, ANTIGEN_PROCESSING_AND_PRESENTATION_OF_EXOGENOUS_PEPTIDE_ANTIGEN_VIA_MHC_CLASS_I, "antigen_processing")

fcRec <- str_to_title(pathways.go$GO_FC_RECEPTOR_SIGNALING_PATHWAY)
saveHeatMaps(all.xls, FC_RECEPTOR_SIGNALING_PATHWAY, "fc_receptor_signaling")

gluRecSig <- str_to_title(pathways.go$GO_GLUTAMATE_RECEPTOR_SIGNALING_PATHWAY)
saveHeatMaps(all.xls, GLUTAMATE_RECEPTOR_SIGNALING_PATHWAY, "glutamate_receptor_signaling_pathway")

macAuto <- str_to_title(pathways.go$GO_MACROAUTOPHAGY)
saveHeatMaps(all.xls, MACROAUTOPHAGY, "macroautophagy")
```

```{r}

```


```{r}
plotWidth <- 9
plotHeight <- (1.2)*plotWidth
hMaps.splicing <- makeHeatMap(all.xls, rnaSplicing)
pdf(file = "~/Google Drive/psp/analysis/plots/combined/heatmap_splicingRaw.pdf",   
    width = plotWidth, # The width of the plot in inches
    height = plotHeight) # The height of the plot in inches
hMaps.splicing[[1]]
dev.off()

pdf(file = "~/Google Drive/psp/analysis/plots/combined/heatmap_splicingAv.pdf",   
    width = plotWidth, # The width of the plot in inches
    height = plotHeight) # The height of the plot in inches
hMaps.splicing[[2]]
dev.off()

pdf(file = "~/Google Drive/psp/analysis/plots/combined/heatmap_splicingAv_TAU_LFC.pdf",   
    width = 1.5, # The width of the plot in inches
    height = plotHeight) # The height of the plot in inches
hMaps.splicing[[3]]
dev.off()

pdf(file = "~/Google Drive/psp/analysis/plots/combined/heatmap_splicingAv_LFC.pdf",   
    width = plotWidth, # The width of the plot in inches
    height = plotHeight) # The height of the plot in inches
hMaps.splicing[[4]]
dev.off()

hMaps.ribo <- makeHeatMap(all.xls, cytosolicRibosome)
pdf(file = "~/Google Drive/psp/analysis/plots/combined/heatmap_ribosomeRaw.pdf",  
    width = plotWidth, # The width of the plot in inches
    height = plotHeight) # The height of the plot in inches
hMaps.ribo[[1]]
dev.off()

pdf(file = "~/Google Drive/psp/analysis/plots/combined/heatmap_ribosomeAv.pdf",  
    width = plotWidth, # The width of the plot in inches
    height = plotHeight) # The height of the plot in inches
hMaps.ribo[[2]]
dev.off()

pdf(file = "~/Google Drive/psp/analysis/plots/combined/heatmap_ribosomeAv_TAU_LFC.pdf",  
    width = 1.5, # The width of the plot in inches
    height = plotHeight) # The height of the plot in inches
hMaps.ribo[[3]]
dev.off()

pdf(file = "~/Google Drive/psp/analysis/plots/combined/heatmap_ribosomeAv_LFC.pdf",  
    width = plotWidth, # The width of the plot in inches
    height = plotHeight) # The height of the plot in inches
hMaps.ribo[[4]]
dev.off()


hMaps.glutSyn <- makeHeatMap(all.xls, glutSyn)
pdf(file = "~/Google Drive/psp/analysis/plots/combined/heatmap_glutamatergicSynapseRaw.pdf",  
    width = plotWidth, # The width of the plot in inches
    height = plotHeight*1.75) # The height of the plot in inches
hMaps.glutSyn[[1]]
dev.off()

pdf(file = "~/Google Drive/psp/analysis/plots/combined/heatmap_glutamatergicSynapseAv.pdf",  
    width = plotWidth, # The width of the plot in inches
    height = plotHeight*1.75) # The height of the plot in inches
hMaps.glutSyn[[2]]
dev.off()

pdf(file = "~/Google Drive/psp/analysis/plots/combined/heatmap_glutamatergicSynapseAv_TAU_LFC.pdf",  
    width = 1.5, # The width of the plot in inches
    height = plotHeight*1.75) # The height of the plot in inches
hMaps.glutSyn[[3]]
dev.off()

pdf(file = "~/Google Drive/psp/analysis/plots/combined/heatmap_glutamatergicSynapseAv_LFC.pdf",  
    width = plotWidth, # The width of the plot in inches
    height = plotHeight*1.75) # The height of the plot in inches
hMaps.glutSyn[[4]]
dev.off()

hMaps.vgc <- makeHeatMap(all.xls, vgc)
pdf(file = "~/Google Drive/psp/analysis/plots/combined/heatmap_voltageGatedIonChannelRaw.pdf",  
    width = plotWidth, # The width of the plot in inches
    height = plotHeight) # The height of the plot in inches
hMaps.vgc[[1]]
dev.off()

pdf(file = "~/Google Drive/psp/analysis/plots/combined/heatmap_voltageGatedIonChannelAv.pdf",  
    width = plotWidth, # The width of the plot in inches
    height = plotHeight) # The height of the plot in inches
hMaps.vgc[[2]]
dev.off()

pdf(file = "~/Google Drive/psp/analysis/plots/combined/heatmap_voltageGatedIonChannelAv_TAU_LFC.pdf",  
    width = 1.5, # The width of the plot in inches
    height = plotHeight) # The height of the plot in inches
hMaps.vgc[[3]]
dev.off()

pdf(file = "~/Google Drive/psp/analysis/plots/combined/heatmap_voltageGatedIonChannelAv_LFC.pdf",  
    width = plotWidth, # The width of the plot in inches
    height = plotHeight) # The height of the plot in inches
hMaps.vgc[[4]]
dev.off()

```



```{r}

all.xls <- all.xls %>% mutate(anySig = ifelse(P.Value.WT.over.Het.x < pVal | P.Value.WT.over.KO.x < pVal | P.Value.WT.over.Het.y < pVal | P.Value.WT.over.KO.y < pVal | P.Value.WT.over.Het < pVal | P.Value.WT.over.KO < pVal, 1, 0))
all.xls <- all.xls %>% mutate(allSig = ifelse(P.Value.WT.over.Het.x < pVal & P.Value.WT.over.KO.x < pVal & P.Value.WT.over.Het.y < pVal & P.Value.WT.over.KO.y < pVal & P.Value.WT.over.Het < pVal & P.Value.WT.over.KO < pVal, 1, 0))
all.xls <- all.xls %>% mutate(allKoSig = ifelse(P.Value.WT.over.KO.x < pVal & P.Value.WT.over.KO.y < pVal & P.Value.WT.over.KO < pVal, 1, 0))
all.lfcs <- all.xls  %>% filter(splicing==1 | cytosolicRibosome==1) %>% select(logFC.Het.over.WT.x, 
                               logFC.KO.over.WT.x, 
                               logFC.Het.over.WT.y, 
                               logFC.KO.over.WT.y, 
                               logFC.Het.over.WT, 
                               logFC.KO.over.WT,
                               geneSymbol
                               )
colnames(all.lfcs) <- c("hetOverWt.trio", "koOverWt.trio", "hetOverWt.shank3", "koOverWt.shank3","hetOverWt.grin2a", "koOverWt.grin2a", "geneSymbol")
all.lfcs.m <- melt(all.lfcs, id="geneSymbol")

# all.sigs.m <- melt(
#   all.xls %>% filter(splicing==1 | cytosolicRibosome==1) %>% select(P.Value.WT.over.Het.x,
#                                P.Value.WT.over.KO.x,
#                                P.Value.WT.over.Het.y,
#                                P.Value.WT.over.KO.y,
#                                P.Value.WT.over.Het,
#                                P.Value.WT.over.KO)
#   )

all.sigs.m <- melt(all.xls %>% filter(splicing==1 | cytosolicRibosome==1) %>% select(allKoSig))

all.lfcs.m$pVal <- all.sigs.m$value

source("~/Google Drive/psp/functions/setTheme.R")
gp <- ggplot(data = all.lfcs.m, aes(x=variable, y=value, group=geneSymbol, color=as.factor(pVal)))
gp <- gp + th
gp <- gp + geom_beeswarm(show.legend = FALSE)
gp <- gp + geom_line(show.legend = FALSE)
gp <- gp + scale_color_manual(values=c('gray90', 'black'))
gp <- gp + ylab("Log2 fold change")
gp <- gp + theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))
gp <- gp + scale_y_continuous(breaks = scales::pretty_breaks(n = 10))
xLab <- c("Trio (Het/WT)", "Trio (KO/WT)", "Shank3 (Het/WT)", "Shank3 (KO/WT)", "Grin2a (Het/WT)", "Grin2a (KO/WT)")
gp <- gp + scale_x_discrete(labels=xLab)
gp <- gp + geom_text_repel(aes(label=ifelse((pVal==1 & variable=="koOverWt.grin2a"), as.character(geneSymbol), '')), show.legend = FALSE, segment.color='black', segment.size = .5, segment.alpha = .25)
gp <- gp + theme(axis.title.x=element_blank())
gp
ggsave(plot = gp, "~/Google Drive/psp/analysis/plots/combined/discrete_sig_all_ko_rna_splicing_ribosome.pdf", width = 8, height = 6, units = "in")

```
```{r}
all.xls <- full_join(trio.xls, shank3.xls, by="id")
all.xls <- full_join(all.xls, grin2a.xls, by="id")
schemaGenes <- c("Rbfox1", "Rbfox2", "Rbfox3")
#all.xls <- all.xls %>% mutate(anySig = ifelse(geneSymbol=="Srrm2", 1, 0))
all.xls <- all.xls %>% mutate(anySig = ifelse(geneSymbol %in% schemaGenes, 1, 0))

# schemaGenes <- as.factor(c("Setd1a", "Cul1", "Xpo7", "Trio", "Cacna1g", "Sp4", "Gria3", "Grin2a", "Herc1", "Rb1cc1", "Hcn4", "Akap11", "Znf136", "Srrm2", "Nr3c2", "Zmym2", "Fam120a", "Slf2", "Kdm6b", "Dnm3", "Ash1l", "Stag1", "Hist1h1e", "Prep", "Magec1", "Magi2", "Dagla", "Or4p4", "Slc22a11", "Ankrd12", "Eif2s3x", "Eif2s3y"))

all.lfcs <- all.xls  %>% filter(geneSymbol %in% schemaGenes | geneSymbol.x %in% schemaGenes | geneSymbol.y %in% schemaGenes) %>% select(logFC.Het.over.WT.x, 
                               logFC.KO.over.WT.x, 
                               logFC.Het.over.WT.y, 
                               logFC.KO.over.WT.y, 
                               logFC.Het.over.WT, 
                               logFC.KO.over.WT,
                               id,
                               geneSymbol,
                               geneSymbol.x,
                               geneSymbol.y
                               )
all.geneSymbols <- all.lfcs %>% select(geneSymbol, geneSymbol.x, geneSymbol.y)
unique_geneSymbols <- sapply(apply(all.geneSymbols[,-1],1, unique),function(x) paste(na.omit(x),collapse = ""))
all.lfcs <- all.lfcs %>% mutate(gId = unique_geneSymbols)

all.lfcs <- all.lfcs %>% mutate(gId = paste(gId,id, sep="_"), .keep="unused")
all.lfcs <- all.lfcs %>% select(-one_of(c('geneSymbol', 'geneSymbol.x', 'geneSymbol.y')))

colnames(all.lfcs) <- c("hetOverWt.trio", "koOverWt.trio", "hetOverWt.shank3", "koOverWt.shank3","hetOverWt.grin2a", "koOverWt.grin2a", "geneSymbol")
all.lfcs.m <- melt(all.lfcs, id="geneSymbol")

all.sigs.m <- melt(all.xls %>% filter(geneSymbol %in% schemaGenes | geneSymbol.x %in% schemaGenes | geneSymbol.y %in% schemaGenes) %>% select(anySig))
all.sigs.m <- all.sigs.m %>% dplyr::mutate(value = replace_na(value, 0))

all.lfcs.m$pVal <- all.sigs.m$value

source("~/Google Drive/psp/functions/setTheme.R")
gp <- ggplot(data = all.lfcs.m, aes(x=variable, y=value, group=geneSymbol, color=as.factor(pVal)))
gp <- gp + th
gp <- gp + geom_beeswarm(show.legend = FALSE)
regp <- gp + geom_line(show.legend = FALSE)
gp <- gp + scale_color_manual(values=c('gray90', 'black'))
gp <- gp + ylab("Log2 fold change")
gp <- gp + theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))
gp <- gp + scale_y_continuous(breaks = scales::pretty_breaks(n = 10))
gp <- gp + coord_cartesian(ylim=c(-2,2))
xLab <- c("Trio (Het/WT)", "Trio (KO/WT)", "Shank3 (Het/WT)", "Shank3 (KO/WT)", "Grin2a (Het/WT)", "Grin2a (KO/WT)")
gp <- gp + scale_x_discrete(labels=xLab)
gp <- gp + geom_text_repel(aes(label=ifelse((variable=="koOverWt.grin2a"), as.character(geneSymbol), '')), show.legend = FALSE, segment.color='black', segment.size = .5, segment.alpha = .25)
gp <- gp + theme(axis.title.x=element_blank())
gp
# ggsave(plot = gp, "~/Google Drive/psp/analysis/plots/combined/discrete_scz_genes.pdf", width = 8, height = 6, units = "in")

```

```{r}
all.xls <- all.xls %>% mutate(anySig = ifelse(P.Value.WT.over.Het.x < pVal | P.Value.WT.over.KO.x < pVal | P.Value.WT.over.Het.y < pVal | P.Value.WT.over.KO.y < pVal | P.Value.WT.over.Het < pVal | P.Value.WT.over.KO < pVal, 1, 0))
all.xls <- all.xls %>% mutate(allSig = ifelse(P.Value.WT.over.Het.x < pVal & P.Value.WT.over.KO.x < pVal & P.Value.WT.over.Het.y < pVal & P.Value.WT.over.KO.y < pVal & P.Value.WT.over.Het < pVal & P.Value.WT.over.KO < pVal, 1, 0))


threshold <- -2
all.xls <- all.xls  %>% mutate(anyNeg = ifelse(logFC.KO.over.WT.x < threshold | logFC.KO.over.WT.y < threshold | logFC.KO.over.WT < threshold | logFC.Het.over.WT.x < threshold | logFC.Het.over.WT.y < threshold | logFC.Het.over.WT < threshold, 1, 0))
all.xls <- all.xls  %>% mutate(allNeg = ifelse(logFC.KO.over.WT.x < threshold & logFC.KO.over.WT.y < threshold & logFC.KO.over.WT < threshold & logFC.Het.over.WT.x < threshold & logFC.Het.over.WT.y < threshold & logFC.Het.over.WT < threshold, 1, 0))

all.lfcs <- all.xls  %>% filter(anyNeg==1) %>% select(logFC.Het.over.WT.x, 
                               logFC.KO.over.WT.x, 
                               logFC.Het.over.WT.y, 
                               logFC.KO.over.WT.y, 
                               logFC.Het.over.WT, 
                               logFC.KO.over.WT,
                               id,
                               geneSymbol
                               ) 
all.lfcs <- all.lfcs %>% mutate(gId = paste(geneSymbol,id, sep="_"), .keep="unused")
colnames(all.lfcs) <- c("hetOverWt.trio", "koOverWt.trio", "hetOverWt.shank3", "koOverWt.shank3","hetOverWt.grin2a", "koOverWt.grin2a", "geneSymbol")
all.lfcs.m <- melt(all.lfcs, id="geneSymbol")

all.sigs <- all.xls %>% filter(anyNeg==1) %>% select(anySig)
all.sigs.m <- melt(all.sigs)
all.sigs.m <- all.sigs.m %>% dplyr::mutate(value = replace_na(value, 0))

all.lfcs.m$pVal <- all.sigs.m$value

source("~/Google Drive/psp/functions/setTheme.R")
gp <- ggplot(data = all.lfcs.m, aes(x=variable, y=value, group=geneSymbol, color=as.factor(pVal)))
gp <- gp + th
gp <- gp + geom_beeswarm(show.legend = FALSE)
gp <- gp + geom_line(show.legend = FALSE)
gp <- gp + scale_color_manual(values=c('gray90', 'black'))
gp <- gp + ylab("Log2 fold change")
gp <- gp + theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))
gp <- gp + scale_y_continuous(breaks = scales::pretty_breaks(n = 10))
#gp <- gp + coord_cartesian(ylim=c(-5,5))
xLab <- c("Trio (Het/WT)", "Trio (KO/WT)", "Shank3 (Het/WT)", "Shank3 (KO/WT)", "Grin2a (Het/WT)", "Grin2a (KO/WT)")
gp <- gp + scale_x_discrete(labels=xLab)
#gp <- gp + geom_text_repel(aes(label=ifelse((variable=="koOverWt.grin2a"), as.character(geneSymbol), '')), show.legend = FALSE, segment.color='black', segment.size = .5, segment.alpha = .25)
gp <- gp + theme(axis.title.x=element_blank())
gp
ggsave(plot = gp, "~/Google Drive/psp/analysis/plots/combined/discrete_neg_log2fold_1.pdf", width = 8, height = 6, units = "in")

```
